name: Polybot Infrastructure Terraform Specific Region

on:
  workflow_call:
    inputs:
      region-code:
        required: true
        type: string
      telegram-token-secret-name:
        required: true
        type: string

jobs:
  Terraform:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    defaults:
      run:
        working-directory: ./tf  # The directory containing your Terraform configuration files
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.0

      - name: Terraform init
        run: terraform init

      - name: Terraform workspace select
        run: terraform workspace select ${{ inputs.region-code }} || terraform workspace new ${{ inputs.region-code }}

      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan
        run: | 
          
          # Setting an environment variable with the prefix TF_VAR_ allows you to define a Terraform variable externally.
          # Assign the value of the secret specified by `telegram-token-secret-name` to the Terraform variable `botToken`. 
          export TF_VAR_botToken=${{ secrets[inputs.telegram-token-secret-name] }}
          
          terraform plan -var-file=region.${{ inputs.region-code }}.tfvars

      - name: Terraform apply
        run: |
          export TF_VAR_botToken=${{ secrets[inputs.telegram-token-secret-name] }}
          terraform apply -auto-approve -var-file=region.${{ inputs.region-code }}.tfvars
